// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rukeqkqpdplastrgvtdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1a2Vxa3FwZHBsYXN0cmd2dGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MjkyOTcsImV4cCI6MjA1MDMwNTI5N30.2WYRB_4IMqenJrwbk2KCf_mI9kymaKj8gvhhnGqMCwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);